<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net6.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Twilio.Video</PackageId>
		<PackageVersion>7.6.1</PackageVersion>
		<AssemblyVersion>7.6.1</AssemblyVersion>
		<FileVersion>7.6.1</FileVersion>
		<Version>7.6.1</Version>
		<Title>Anjo Android Twilio Video SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Twilio.Video</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Twilio Video SDK</Description>
		<PackageReleaseNotes>Twilio Video SDK v7.6.1</PackageReleaseNotes>
		<Copyright>Copyright (c) 2023 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, Twilio, Voice_Call, Video_Call</PackageTags>
		<Summary>Twilio Video is a programmable real-time communications platform that allows you to add video chat functionality to your Android application. The platform provides APIs, SDKs, and helper tools to capture, distribute, record, and render high quality audio and video applications</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\video-android-7.6.1.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.6.0" />
	  <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="1.8.20" />
	  <PackageReference Include="Xamarin.ReLinker" Version="1.4.4" />
	</ItemGroup>
</Project>